package com.zg.netflixloginscreenjetpackcompose.ui.theme

import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

// Dimens
val MARGIN_SMALL_2X = 2.dp
val MARGIN_SMALL = 4.dp
val MARGIN_MEDIUM  = 8.dp
val MARGIN_CARD_MEDIUM_2 = 12.dp
val MARGIN_MEDIUM_2 = 16.dp
val MARGIN_MEDIUM_3 = 20.dp
val MARGIN_LARGE = 24.dp
val MARGIN_LARGE_2X = 28.dp
val MARGIN_XLARGE = 32.dp
val MARGIN_XXLARGE = 48.dp

val NETFLIX_LOGO_SIZE = 130.dp
val CATEGORY_BUTTON_HEIGHT = 32.dp
val HOME_SCREEN_CATEGORY_BORDER_WIDTH = 0.5.dp

val HOME_SCREEN_CATEGORIES_TOP_MARGIN = 88.dp
val MOBILE_GAME_ITEM_SIZE = 118.dp
val HOME_SCREEN_MOVIE_IMAGE_WIDTH = 120.dp
val HOME_SCREEN_MOVIE_IMAGE_HEIGHT = 180.dp
val HOME_SCREEN_SUB_TEXT_WIDTH = 76.dp
val CONTINUE_WATCHING_PLAY_BUTTON_SIZE = 56.dp
val CONTINUE_WATCHING_PLAY_ICON_SIZE = 40.dp

val BOTTOM_NAVIGATION_BAR_HEIGHT = 68.dp

// Text
val TEXT_SMALL_3X = 8.sp
val TEXT_SMALL_2X = 10.sp
val TEXT_SMALL = 12.sp
val TEXT_REGULAR = 14.sp
val TEXT_REGULAR_2X = 16.sp
val TEXT_REGULAR_3X = 20.sp
val TEXT_LARGE = 24.sp
val TEXT_BIG = 32.sp

val LINE_HEIGHT_SMALL_3X = 8.sp
val LINE_HEIGHT_SMALL_2X = 10.sp
val LINE_HEIGHT_SMALL = 14.sp
val LINE_HEIGHT_REGULAR = 18.sp
